# Generated by Django 2.1.7 on 2021-08-21 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 21, 16, 55, 51, 856716))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 8, 21, 16, 55, 51, 856747))),
                ('fav', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=40)),
                ('startday', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['startday'],
            },
        ),
        migrations.AlterIndexTogether(
            name='language',
            index_together={('fav', 'like')},
        ),
    ]
