# Generated by Django 2.1.7 on 2021-08-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=40)),
            ],
        ),
    ]
