# Generated by Django 2.1.7 on 2021-08-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like1', models.CharField(max_length=40)),
                ('like2', models.CharField(max_length=40)),
            ],
        ),
    ]
