# Generated by Django 2.1.7 on 2021-08-21 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210821_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 12, 34, 47, 136481)),
        ),
        migrations.AlterField(
            model_name='language',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
